# Generated by Django 4.2.17 on 2025-02-01 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='顯示順位')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='菜單名稱')),
                ('name', models.CharField(blank=True, default='name', max_length=50, unique=True, verbose_name='菜單路由名稱')),
                ('path', models.CharField(blank=True, default='path', max_length=50, unique=True, verbose_name='菜單路由路徑')),
                ('component', models.CharField(blank=True, default='component', max_length=50, unique=True, verbose_name='菜單路由組件')),
                ('redirect', models.CharField(blank=True, max_length=50, null=True, verbose_name='跳轉路徑')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='菜單圖案')),
                ('is_menu', models.BooleanField(blank=True, default=True, verbose_name='是否為菜單')),
                ('is_disabled', models.BooleanField(blank=True, default=False, verbose_name='是否停用')),
                ('deleted_by_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menu')),
            ],
            options={
                'db_table': 'menus',
                'ordering': ['priority'],
            },
        ),
    ]
