# Generated by Django 4.2.17 on 2025-02-01 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, db_comment='菜單路由組件', default='component', max_length=50, unique=True, verbose_name='菜單路由組件'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, db_comment='菜單圖案', max_length=50, null=True, verbose_name='菜單圖案'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_disabled',
            field=models.BooleanField(blank=True, db_comment='是否停用', default=False, verbose_name='是否停用'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_menu',
            field=models.BooleanField(blank=True, db_comment='是否為菜單', default=True, verbose_name='是否為菜單'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, db_comment='菜單路由名稱', default='name', max_length=50, unique=True, verbose_name='菜單路由名稱'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, db_comment='父級菜單ID', help_text='選擇此菜單項目的父級菜單', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menu', verbose_name='父級菜單'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, db_comment='菜單路由路徑', default='path', max_length=50, unique=True, verbose_name='菜單路由路徑'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='priority',
            field=models.IntegerField(blank=True, db_comment='顯示順位', null=True, verbose_name='顯示順位'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='redirect',
            field=models.CharField(blank=True, db_comment='跳轉路徑', max_length=50, null=True, verbose_name='跳轉路徑'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, db_comment='菜單名稱', max_length=50, verbose_name='菜單名稱'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['priority'], name='menus_priorit_e34b67_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['parent', 'priority'], name='menus_parent__3e900d_idx'),
        ),
    ]
