# Generated by Django 4.2.17 on 2025-02-01 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_alter_menu_component_alter_menu_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='新增時間'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='刪除時間', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='deleted_by_user',
            field=models.ForeignKey(blank=True, db_comment='刪除用戶', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否被軟刪除', default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新時間'),
        ),
    ]
