# Generated by Django 4.2.17 on 2025-02-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_created_at_alter_menu_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, db_comment='菜單路由組件', default='component', max_length=50, null=True, unique=True, verbose_name='菜單路由組件'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, db_comment='菜單路由名稱', default='name', max_length=50, null=True, unique=True, verbose_name='菜單路由名稱'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, db_comment='菜單路由路徑', default='path', max_length=50, null=True, unique=True, verbose_name='菜單路由路徑'),
        ),
    ]
