# Generated by Django 4.2.17 on 2025-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_component_alter_menu_name_alter_menu_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, db_comment='菜單路由組件', max_length=50, null=True, verbose_name='菜單路由組件'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, db_comment='菜單路由名稱', max_length=50, null=True, verbose_name='菜單路由名稱'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, db_comment='菜單路由路徑', max_length=50, null=True, verbose_name='菜單路由路徑'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('name',), name='unique_name_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(('path__isnull', False)), fields=('path',), name='unique_path_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(('component__isnull', False)), fields=('component',), name='unique_component_when_not_null'),
        ),
    ]
