# Generated by Django 4.2.17 on 2025-02-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_directory',
            field=models.BooleanField(blank=True, db_comment='是否為目錄', default=False, verbose_name='是否為目錄'),
        ),
    ]
