# Generated by Django 4.2.17 on 2025-02-22 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='新增時間')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新時間')),
                ('line_id', models.CharField(db_comment='LINE ID', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(db_comment='顯示名稱', max_length=255)),
                ('picture_url', models.URLField(blank=True, db_comment='頭像', max_length=1024, null=True)),
                ('email', models.EmailField(blank=True, db_comment='電子郵件', max_length=254, null=True)),
                ('access_token', models.TextField(db_comment='存取權杖')),
                ('token_expires_at', models.DateTimeField(db_comment='權杖過期時間')),
                ('last_login', models.DateTimeField(db_comment='最後登入時間', default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, db_comment='用戶', on_delete=django.db.models.deletion.CASCADE, related_name='line_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LINE 用戶',
                'verbose_name_plural': 'LINE 用戶',
                'db_table': 'line_user',
            },
        ),
    ]
