# Generated by Django 4.2.17 on 2025-01-26 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name_zh', models.CharField(blank=True, max_length=100, unique=True, verbose_name='群組名稱')),
                ('deleted_by_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'db_table': 'group_profile',
            },
        ),
        migrations.AddConstraint(
            model_name='groupprofile',
            constraint=models.UniqueConstraint(fields=('name_zh', 'group', 'deleted_at'), name='unique_group_name_deleted_at'),
        ),
    ]
