# Generated by Django 4.2.17 on 2025-01-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'verbose_name': '角色訊息', 'verbose_name_plural': '角色訊息列表'},
        ),
    ]
