# Generated by Django 4.2.17 on 2025-02-01 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('group', '0002_alter_groupprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='刪除時間', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='deleted_by_user',
            field=models.ForeignKey(blank=True, db_comment='刪除用戶', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='group',
            field=models.OneToOneField(db_comment='角色代號', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否被軟刪除', default=False),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='name_zh',
            field=models.CharField(blank=True, db_comment='角色名稱', max_length=100, unique=True, verbose_name='角色名稱'),
        ),
    ]
