# Generated by Django 4.2.17 on 2025-02-01 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_comment='使用者帳號', max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, db_comment='電子郵件', max_length=254, null=True)),
                ('is_staff', models.BooleanField(db_comment='是否為管理員', default=False)),
                ('is_active', models.BooleanField(db_comment='是否啟用', default=True)),
                ('date_joined', models.DateTimeField(db_comment='註冊時間', default=django.utils.timezone.now)),
                ('first_name', models.CharField(blank=True, db_comment='名字', max_length=30, verbose_name='名字')),
                ('last_name', models.CharField(blank=True, db_comment='姓氏', max_length=30, null=True, verbose_name='姓氏')),
                ('phone', models.CharField(blank=True, db_comment='聯絡電話', max_length=15, null=True, verbose_name='聯絡電話')),
                ('gender', models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性'), ('O', '其他'), ('N', '不公開')], db_comment='性別', default='N', max_length=1, verbose_name='性別')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用戶',
                'verbose_name_plural': '用戶列表',
                'db_table': 'user',
                'permissions': [('export_user', '匯出使用者')],
            },
        ),
        migrations.CreateModel(
            name='UserDeactivateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='新增時間')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新時間')),
                ('deactivate_date', models.DateField(blank=True, db_comment='註銷日期', default=django.utils.timezone.now, verbose_name='註銷日期')),
                ('reason', models.TextField(blank=True, db_comment='註銷原因', null=True, verbose_name='註銷原因')),
                ('created_by_user', models.ForeignKey(blank=True, db_comment='創建用戶', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, db_comment='修改用戶', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_comment='使用者ID', on_delete=django.db.models.deletion.CASCADE, related_name='deactivate_logs', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者註銷紀錄',
                'verbose_name_plural': '使用者註銷紀錄',
                'db_table': 'user_deactivate_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
