# Generated by Django 4.2.17 on 2025-02-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name'], name='user_first_n_3f9974_idx'),
        ),
    ]
