# Generated by Django 4.2.17 on 2025-01-31 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdeactivationlog_updated_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeactivationlog',
            name='deactivate_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='註銷日期'),
        ),
        migrations.AlterField(
            model_name='userdeactivationlog',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='註銷原因'),
        ),
    ]
