# Generated by Django 4.2.17 on 2025-01-31 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdeactivationlog_deactivate_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeactivateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivate_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='註銷日期')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='註銷原因')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivate_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者註銷紀錄',
                'verbose_name_plural': '使用者註銷紀錄',
                'db_table': 'user_deactivate_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserDeactivationLog',
        ),
    ]
