from decouple import config

# LineBot Webhook
LINE_CHANNEL_ACCESS_TOKEN = config('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = config('LINE_CHANNEL_SECRET')


# Line Login
LINE_LOGIN_CHANNEL_ID = config('LINE_LOGIN_CHANNEL_ID')
LINE_LOGIN_CHANNEL_SECRET = config('LINE_LOGIN_CHANNEL_SECRET')
LINE_LOGIN_CALLBACK_URL = config('LINE_LOGIN_CALLBACK_URL')