# Generated by Django 4.2.17 on 2025-01-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_post_created_by_post_record_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': '貼文訊息', 'verbose_name_plural': '貼文訊息列表'},
        ),
    ]
