# Generated by Django 4.2.17 on 2025-01-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='created_by_user',
        ),
    ]
