# Generated by Django 4.2.17 on 2025-02-11 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_alter_post_created_at_alter_post_created_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, db_comment='修改用戶', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
