# Generated by Django 4.2.17 on 2025-02-18 03:35

import common.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='name',
            field=models.CharField(blank=True, db_comment='檔名', error_messages={'unique': '這個檔名已經存在。'}, help_text='可選。如果不指定，將使用上傳的原始檔名', max_length=255, null=True, unique=True, verbose_name='檔名'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='path',
            field=models.ImageField(blank=True, db_comment='圖片路徑', help_text='支援的格式：JPG, JPEG, PNG, GIF, WebP', null=True, upload_to=common.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message='只允許上傳 jpg, jpeg, png, gif, webp 格式的圖片'), common.models.validate_image_size], verbose_name='路徑'),
        ),
    ]
